apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-config
  namespace: troubleshooting-lab
data:
  default.conf: |
    server {
      listen 80;
      location / {
        return 200 'nginx config mounted successfully\n';
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-config-demo
  namespace: troubleshooting-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume-config-demo
  template:
    metadata:
      labels:
        app: volume-config-demo
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-custom-config

