apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptydir-demo
  namespace: troubleshooting-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emptydir-demo
  template:
    metadata:
      labels:
        app: emptydir-demo
    spec:
      containers:
        - name: app
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - date > /cache/start-time.txt; echo "file created in emptyDir"; sleep 3600
          volumeMounts:
            - name: cache
              mountPath: /cache
      volumes:
        - name: cache
          emptyDir: {}

