apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-selector-demo
  namespace: troubleshooting-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-selector-demo
  template:
    metadata:
      labels:
        app: node-selector-demo
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80

